CREATE OR REPLACE PROCEDURE eureka.spCuenta
(p_codigo NUMBER,p_saldo OUT NUMBER,p_moneda OUT NUMBER  )
IS
BEGIN
SELECT DEC_CUENSALDO,CHR_MONECODIGO INTO p_saldo, p_moneda
	FROM EUREKA.CUENTA
	WHERE CHR_CUENCODIGO = p_codigo;
END;



