
CREATE OR REPLACE PACKAGE eureka.PKG_MOV IS

TYPE T_CURSOR IS REF CURSOR;

PROCEDURE GET_MOV(
  Cuenta IN  eureka.MOVIMIENTO.CHR_CUENCODIGO%TYPE,
  F1 IN  eureka.MOVIMIENTO.DTT_MOVIFECHA%TYPE,
  F2 IN  eureka.MOVIMIENTO.DTT_MOVIFECHA%TYPE,
  P_CURSOR OUT T_CURSOR
);

END;
/


CREATE OR REPLACE PACKAGE BODY eureka.PKG_MOV IS

PROCEDURE GET_MOV(
  Cuenta IN  eureka.MOVIMIENTO.CHR_CUENCODIGO%TYPE,
  F1 IN  eureka.MOVIMIENTO.DTT_MOVIFECHA%TYPE,
  F2 IN  eureka.MOVIMIENTO.DTT_MOVIFECHA%TYPE,
  P_CURSOR OUT T_CURSOR
)
is
begin
open P_CURSOR FOR 
select 
  CHR_CUENCODIGO,INT_MOVINUMERO,DTT_MOVIFECHA,
  CHR_EMPLCODIGO,CHR_TIPOCODIGO,DEC_MOVIIMPORTE,CHR_CUENREFERENCIA from EUREKA.MOVIMIENTO
where CHR_CUENCODIGO=Cuenta 
and DTT_MOVIFECHA between F1 and F2;
end;

END;

BEGIN
	EUREKA.PKG_MOV.GET_MOV ('00100001', to_date ('2008-01-01', 'YYYY-MM-DD'), to_date ('2008-01-31', 'YYYY-MM-DD'), :p_cursor$REFCURSOR);
END;