CREATE OR REPLACE PACKAGE EUREKA.PK_CUENTA_R 
IS
   TYPE T_CURSOR IS REF CURSOR; 
   PROCEDURE SP_CTAS(P_CTA VARCHAR, P_FE_INI VARCHAR, P_FE_FIN VARCHAR, P_CURSOR OUT T_CURSOR);
END;



--BODY
CREATE OR REPLACE PACKAGE BODY EUREKA.PK_CUENTA_R 
IS
   
PROCEDURE SP_CTAS(P_CTA VARCHAR,P_FE_INI VARCHAR, P_FE_FIN VARCHAR, P_CURSOR OUT T_CURSOR)
IS
    
  V_FE_INI DATE := TO_DATE(P_FE_INI,'DD/MM/YYYY');
  V_FE_FIN DATE := TO_DATE(P_FE_FIN,'DD/MM/YYYY');

BEGIN
  
  OPEN P_CURSOR FOR
  SELECT B.*
    FROM EUREKA.CUENTA A  
         INNER JOIN EUREKA.MOVIMIENTO B ON A.CHR_CUENCODIGO = B.CHR_CUENCODIGO 
  WHERE A.CHR_CUENCODIGO = P_CTA
    AND DTT_MOVIFECHA BETWEEN V_FE_INI AND V_FE_FIN; 
   
END;

END;


BEGIN
	EUREKA.PK_CUENTA_R.SP_CTAS ('00100001','01/01/2008','30/03/2018',:p_cursor$REFCURSOR);
END;



/*
SELECT B.*
    FROM EUREKA.CUENTA A  
         INNER JOIN EUREKA.MOVIMIENTO B ON A.CHR_CUENCODIGO = B.CHR_CUENCODIGO 
  WHERE A.CHR_CUENCODIGO = '00100001'
    AND DTT_MOVIFECHA BETWEEN TO_DATE('01/01/2008','DD/MM/YYYY') AND TO_DATE('30/03/2018','DD/MM/YYYY'); 
   
*/