
--RENSO CONTRERAS SAMANIEGO

/*
EJERCICIO
Crear un paquete para consultar los movimientos de una cuenta por rango de fecha
*/


CREATE OR REPLACE PACKAGE EUREKA.PKG_MOVCUENTA IS
TYPE T_CURSOR IS REF CURSOR;

PROCEDURE GET_MOVCUENTA(
CODIGO   IN  EUREKA.MOVIMIENTO.CHR_CUENCODIGO%TYPE,
FechaIn  IN  EUREKA.MOVIMIENTO.DTT_MOVIFECHA%TYPE,
FechaFi  IN  EUREKA.MOVIMIENTO.DTT_MOVIFECHA%TYPE,
P_CURSOR OUT T_CURSOR
);
END PKG_MOVCUENTA;


CREATE OR REPLACE PACKAGE BODY EUREKA.PKG_MOVCUENTA IS

PROCEDURE GET_MOVCUENTA(
CODIGO IN EUREKA.MOVIMIENTO.CHR_CUENCODIGO%TYPE,
FechaIn IN EUREKA.MOVIMIENTO.DTT_MOVIFECHA%TYPE,
FechaFi IN EUREKA.MOVIMIENTO.DTT_MOVIFECHA%TYPE,
P_CURSOR OUT T_CURSOR)
IS
BEGIN
    OPEN P_CURSOR FOR 
    SELECT * FROM EUREKA.MOVIMIENTO
    WHERE CHR_CUENCODIGO = CODIGO AND 
          DTT_MOVIFECHA between FechaIn AND FechaFi;  
END;
END PKG_MOVCUENTA;


DECLARE
    V_CURSOR EUREKA.PKG_MOVCUENTA.T_CURSOR;
    V_REC EUREKA.MOVIMIENTO%ROWTYPE;                 
BEGIN                                                 
    EUREKA.PKG_MOVCUENTA.GET_MOVCUENTA('00100001',
        to_date('20080106 16:40:10','YYYYMMDD HH24:MI:SS'),
        to_date('20080214 16:40:10','YYYYMMDD HH24:MI:SS'),V_CURSOR);
    LOOP
        FETCH V_CURSOR INTO V_REC;
        EXIT WHEN V_CURSOR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_REC.CHR_CUENCODIGO|| ',' || V_REC.DTT_MOVIFECHA );
    END LOOP;
    
    CLOSE V_CURSOR;
END;