CREATE OR REPLACE PROCEDURE UpdateSalEmp
(codigo EMP.EMPNO%TYPE, salario EMP.SAL%TYPE)
IS
cont NUMBER;
BEGIN
SELECT COUNT(*) INTO cont
FROM EMP
WHERE EMPNO = codigo;
IF (cont = 0) THEN
RAISE NO_DATA_FOUND;
END IF;
UPDATE EMP
SET SAL = salario
WHERE EMPNO= codigo;
COMMIT;
DBMS_OUTPUT.PUT_LINE('Proceso OK');
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('Codigo no existe');
END;