
--SELECT * FROM EUREKA.CLIENTE
--SELECT * FROM EUREKA.CUENTA

CREATE OR REPLACE PROCEDURE SP_CTAS(P_CTA VARCHAR)

IS

CURSOR CUR_CTA(P_CTA VARCHAR) IS 
SELECT CHR_CUENCODIGO FROM EUREKA.CUENTA WHERE CHR_CLIECODIGO = P_CTA;

BEGIN


FOR REG IN CUR_CTA(P_CTA) LOOP
   
   DBMS_OUTPUT.PUT_LINE('EMPLEADO: '||REG.CHR_CUENCODIGO);
   
END LOOP;


END;

CALL SP_CTAS('00005');